# Generated by Django 3.2.9 on 2022-01-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0002_auto_20220109_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neigname', models.CharField(max_length=150)),
                ('neiglocation', models.CharField(max_length=150)),
                ('neigcount', models.IntegerField()),
            ],
        ),
    ]
