# Generated by Django 3.2.9 on 2022-01-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0004_ocuupant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('occ_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neigborhood', to='majiraniapp.neighborhood')),
            ],
        ),
        migrations.DeleteModel(
            name='Ocuupant',
        ),
    ]
