# Generated by Django 3.2.9 on 2022-01-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0006_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neigcount',
            field=models.IntegerField(max_length=6),
        ),
    ]
