# Generated by Django 3.2.9 on 2022-01-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0007_alter_neighborhood_neigcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupant',
            name='email',
        ),
    ]
