# Generated by Django 3.2.9 on 2022-01-10 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0010_remove_neighborhood_neigcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('info', models.TextField(max_length=400)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='neigcount',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name=500000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occupant',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
