# Generated by Django 3.2.9 on 2022-01-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0011_auto_20220110_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neigcount',
            field=models.IntegerField(null=True),
        ),
    ]
