# Generated by Django 3.2.9 on 2022-01-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0013_alter_neighborhood_neigcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neigcount',
            field=models.IntegerField(null=True),
        ),
    ]
