# Generated by Django 3.2.9 on 2022-01-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0014_alter_neighborhood_neigcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
