# Generated by Django 3.2.9 on 2022-01-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majiraniapp', '0017_auto_20220113_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='bizz_name',
            new_name='name',
        ),
    ]
